version: '3'
services:
  cyberchef:
    container_name: cyberchef
    image: mpepping/cyberchef:latest
    restart: always
    ports:
      - '8000:8000'
    networks:
      - cyberchef
    expose:
      - '8000'
      
networks:
  cyberchef:
    driver: 'bridge'