CREATE DATABASE IF NOT EXISTS onlyoffice CHARACTER SET "utf8" COLLATE "utf8_general_ci";

CREATE USER IF NOT EXISTS 'onlyoffice_user'@'%' IDENTIFIED BY 'HR3jtKMR6PeX5EcD3FLk';

GRANT ALL PRIVILEGES ON onlyoffice.* TO 'onlyoffice_user'@'%';

FLUSH PRIVILEGES;