version: '3'
services:
  samba:
    container_name: samba
    image: dperson/samba:latest
    environment:
      TZ: 'AEST-9AEDT,M3.2.0/2:00:00,M11.1.0/2:00:00'
    networks:
      - samba
    ports:
      - '137:137/udp'
      - '138:138/udp'
      - '139:139/tcp'
      - '445:445/tcp'
    read_only: true
    tmpfs:
      - /tmp
    restart: unless-stopped
    stdin_open: true
    tty: true
    volumes:
      - /srv/irshare:/mnt:z
    command: '-s "irshare;/mnt;yes;no;no;irshare" -u "irshare;forensics" -p'
      
networks:
  samba:
    driver: 'bridge'